- hosts: localhost
  tasks:
  - name: Executing the Query For DL Jobs
    shell: /etc/ansible/notify_alerts/tasks/notify_about_dlbgjobs_active.sh
    register: dl_active_jobs
  - debug: msg="{{ dl_active_jobs.stdout_lines }}"  
  - debug: msg="{{ dl_active_jobs.stdout.split('\n')[1] }}"
  - name: Sending an e-mail using SMTP servers
    mail:
     host: <SMTP>.amazonaws.com
      port: 587
      username: <USERNAME
      password: <PASSWORD>
      from: <YOUR SMTP DoMAIN MAIL>
      to: <To yourMAIL>
      subject: Monitoring Alert:DL Data Load Jobs are in Active
      subtype: html
      body: '{{ lookup("template", "mail_dl_bgjobs_active.html.j2") }}'
    when: dl_active_jobs.stdout.split('\n')[1] | int >5 
    delegate_to: localhost
